import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ModalProvider } from "@/shared/contexts/ModalContext";
import { LayoutWidget } from "@/widgets/layout/LayoutWidget";
import { ReactQueryProvider } from "@/shared/providers/ReactQueryProvider";
import "../shared/styles/globals.css";
import { Toaster } from "sonner";
import { ModalWidget } from "@/widgets/modal/ModalWidget";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <ModalProvider>
            <LayoutWidget>{children}</LayoutWidget>
            <ModalWidget />
            <Toaster />
          </ModalProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
