import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/shared/styles/globals.css";
import { LayoutWidget } from "@/widgets/layout/LayoutWidget";
import { ModalProvider } from "@/shared/contexts/ModalContext";
import { ModalWidget } from "@/widgets/modal/ModalWidget";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ModalProvider>
          <LayoutWidget>
            {children}
            <ModalWidget />
          </LayoutWidget>
        </ModalProvider>
      </body>
    </html>
  );
}
